import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)));
const indexHtmlPath = join(rootDir, "dist", "index.html");
const outputPath = join(rootDir, "api", "_generated", "clientAssets.js");

function collectAttributes(html, tagPattern, attrName) {
  const values = [];
  const regex = new RegExp(tagPattern, "gi");
  let match = regex.exec(html);

  while (match) {
    const tag = match[0];
    const attrMatch = tag.match(new RegExp(`${attrName}="([^"]+)"`, "i"));
    if (attrMatch?.[1]) values.push(attrMatch[1]);
    match = regex.exec(html);
  }

  return values;
}

const indexHtml = readFileSync(indexHtmlPath, "utf8");
const stylesheets = collectAttributes(
  indexHtml,
  "<link\\s+[^>]*rel=\"stylesheet\"[^>]*>",
  "href"
);
const modulePreloads = collectAttributes(
  indexHtml,
  "<link\\s+[^>]*rel=\"modulepreload\"[^>]*>",
  "href"
);
const scripts = collectAttributes(
  indexHtml,
  "<script\\s+[^>]*type=\"module\"[^>]*src=\"[^\"]+\"[^>]*>",
  "src"
);

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `// Generated by scripts/generateSeoShellAssets.js after vite build.
export const CLIENT_STYLESHEETS = ${JSON.stringify(stylesheets, null, 2)};
export const CLIENT_MODULE_PRELOADS = ${JSON.stringify(modulePreloads, null, 2)};
export const CLIENT_SCRIPTS = ${JSON.stringify(scripts, null, 2)};
`,
  "utf8"
);
