// Generated by scripts/generateSeoShellAssets.js after vite build.
export const CLIENT_STYLESHEETS = [
  "/assets/index-B0gXpQpq.css"
];
export const CLIENT_MODULE_PRELOADS = [];
export const CLIENT_SCRIPTS = [
  "/assets/index-C04neodu.js"
];
